// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbumnxegxvvhittxfdxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpidW1ueGVneHZ2aGl0dHhmZHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0NjQwMDIsImV4cCI6MjA2NjA0MDAwMn0.oLBaSGrglCZSi9c1bHSIocjStoz5RpAjq1AGxRnhszk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);